{{- if or .Values.cron.enabled .Values.exporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "duplicacy.fullname" . }}
  labels:
    {{- include "duplicacy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.cron.storage.endpoint1 }}
  DUPLICACY_S3_ENDPOINT_1: {{ .Values.cron.storage.endpoint1 | quote }}
  {{- end }}
  {{- if .Values.cron.storage.endpoint2 }}
  DUPLICACY_S3_ENDPOINT_2: {{ .Values.cron.storage.endpoint2 | quote }}
  {{- end }}
  {{- if .Values.cron.storage.bucket }}
  DUPLICACY_S3_BUCKET: {{ .Values.cron.storage.bucket | quote }}
  {{- end }}
  {{- if .Values.cron.storage.region }}
  DUPLICACY_S3_REGION: {{ .Values.cron.storage.region | quote }}
  {{- end }}
  {{- range $name, $creds := .Values.cron.credentials }}
  {{- if $creds.s3Id }}
  DUPLICACY_{{ $name }}_S3_ID: {{ $creds.s3Id | quote }}
  {{- end }}
  {{- if $creds.s3Secret }}
  DUPLICACY_{{ $name }}_S3_SECRET: {{ $creds.s3Secret | quote }}
  {{- end }}
  {{- if $creds.password }}
  DUPLICACY_{{ $name }}_PASSWORD: {{ $creds.password | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.cron.notification.shoutrrrUrl }}
  SHOUTRRR_URL: {{ .Values.cron.notification.shoutrrrUrl | quote }}
  {{- end }}
{{- end }}
